name: Generate QR Codes
on: [push]
jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate QR Code with GitHub Pages URL
        run: |
          pip install qrcode[pil]
          python -c "
          import qrcode
          
          # URL to your GitHub Pages site
          github_pages_url = 'https://${{ github.repository_owner }}.github.io/NameCard-QR/'
          
          # Create QR code with your GitHub Pages URL
          qr = qrcode.QRCode(
              version=1,
              error_correction=qrcode.constants.ERROR_CORRECT_L,
              box_size=10,
              border=4,
          )
          qr.add_data(github_pages_url)
          qr.make(fit=True)
          
          # Create and save the QR code image
          img = qr.make_image(fill_color='black', back_color='white')
          img.save('calcium-carbonate-qr.png')
          "
      - name: Upload QR Code
        uses: actions/upload-artifact@v4
        with:
          name: calcium-carbonate-qr
          path: calcium-carbonate-qr.png
