name: Generate QR Codes
on: [push]

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Create minimal index.html (landing page)
      - name: Create index.html
        run: |
          cat > index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>JMSB Products</title>
            <style>
              body { 
                font-family: Arial, sans-serif; 
                max-width: 600px; 
                margin: 20px auto; 
                padding: 20px;
                line-height: 1.6;
                text-align: center;
              }
              .product-link {
                display: block;
                margin: 25px 0;
                padding: 15px;
                background: #f0f8ff;
                border-radius: 8px;
                text-decoration: none;
                color: #0066cc;
                font-weight: bold;
              }
            </style>
          </head>
          <body>
            <h1>JMSB Products</h1>
            <a href="calcium-carbonate.html" class="product-link">
              Calcium Carbonate Powder
            </a>
          </body>
          </html>
          EOF

      # Create calcium-carbonate.html (your exact content)
      - name: Create product page
        run: |
          cat > calcium-carbonate.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>JMSB Calcium Carbonate</title>
            <style>
              body {
                font-family: system-ui, -apple-system, sans-serif;
                max-width: 500px;
                margin: 20px auto;
                padding: 15px;
                line-height: 1.5;
                color: #333;
              }
              .main-line {
                font-size: 1.3em;
                font-weight: bold;
                margin-bottom: 15px;
              }
            </style>
          </head>
          <body>
            <div class="main-line">JMSB Manufacture Calcium Carbonate Powder from Lime Stone.</div>
            <p>Calcium Carbonate use for agriculture soil is a natural fertilizer that works as a soil amendment to soil acidic (low PH) to support plant growth and health.</p>
            <p>Lime stone has been a cornerstone of agriculture for centuries and many of us still do not know the hidden benefits of Calcium Carbonate for soil and plant.</p>
            <p>Email JMSB for further information.</p>
          </body>
          </html>
          EOF

      # Generate QR code
      - name: Generate QR Code
        run: |
          pip install qrcode[pil]
          # Auto-generate GitHub Pages URL
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          PAGE_URL="https://$GITHUB_REPOSITORY_OWNER.github.io/$REPO_NAME/calcium-carbonate.html"
          python -c "
          import qrcode
          qr = qrcode.QRCode(
              version=1,
              error_correction=qrcode.constants.ERROR_CORRECT_L,
              box_size=10,
              border=4,
          )
          qr.add_data('$PAGE_URL')
          qr.make(fit=True)
          img = qr.make_image(fill_color='black', back_color='white')
          img.save('calcium-carbonate-qr.png')
          "

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true

      - name: Upload QR Code
        uses: actions/upload-artifact@v4
        with:
          name: calcium-carbonate-qr
          path: calcium-carbonate-qr.png
